name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - uses: actions/checkout@v2
      # Step 2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      # Step 3
      - name: Install dependencies
        run: npm install
      # Step 4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA4MTWM6BL2RG7IRVC
          aws-secret-access-key: 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
      # Step 5
      - name: Build Application and Run unit Test
        run: python app.py & pytest

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'
    steps:
     # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA4MTWM6BL2RG7IRVC
          aws-secret-access-key: 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
     # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name application-name \
            --deployment-group-name AppDeploymentGroupName \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
