name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest--=
    steps:
    - name: checkout repo
      uses: action/checkout@v2
    - name: copy via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        source: .,!node_modules
        target: ~/app
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 2
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ~/app
          npm install --omit=dev
          pm2 stop all
          pm2 start index.js
